### ISSUE TITLE
Allow update of objects that are too large for kubectl apply command

### ISSUE THREAD

**Issue by lewismarshall** [UKHomeOffice/kd#107]
Optionally support the verb `replace` over `apply` for large objects or objects that need replacing like cronjobs (you want old jobs to be deleted).

This is also useful for large configmaps over ~800K.

Document the flag and also the optional extra args that are useful in some cases:
`-- --save-config=false` and or `-- --force`.

**Comment by Joseph-Irving** [comment]
It's worth making it really obvious that this is a destructive option and shouldn't be used in most cases.

We had a replace option in our deployment tool, originally just for cronjobs as they were immutable at some point or something.  A few repos had this replace option in their .drone.yml and before you know it other people have copied this stage into their projects and are deleting and recreating ingress/deployments/service accounts every time they deploy which is less than ideal.

**Comment by lewismarshall** [comment]
@Joseph-Irving - you think I should call it out in the readme? It is optional and not default... #108

**Comment by Joseph-Irving** [comment]
Yeah I think putting something in the readme about its purpose make sense, could log something as well. I just like making sure users are informed of what the implications of the option are so they don't accidentally break their stuff.

**Comment by lewismarshall** [comment]
Fixed by #108
