### ISSUE TITLE
Keep kd version tag in-line with the kubectl version

### ISSUE THREAD

**Issue by KashifSaadat** [UKHomeOffice/kd#97]
kubectl only officially supports +/-1 version of the Kubernetes Cluster you are interacting with. For kd users, they would currently need to dig through the releases and code to find out which version would be compatible with the cluster they are interacting with.

It may be better to tie the release version of kd with the version of kubectl that is bundled, for example: `v1.10.3_p1`

**Comment by jaykeshur** [comment]
+1 (or have a page similar to cluster-autoscaler) which identifies compatibility

**Comment by lewismarshall** [comment]
This page is still a bit of digging: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases

Maybe `kdv1.0.0_kv1.10.3` so we can maintain with semver meaning for kd too?

**Comment by jaykeshur** [comment]
you wouldnt introduce breaking changes in kd intra kubectl version

**Comment by lewismarshall** [comment]
@jaykeshur - there's no coupling between kd and kubectl and kd can be shipped and used independently of kubectl but for the sake of ease of use for container users in preference and with regards to #69 and #99  - we'll go with that for now...

Going to cook 1.8.0 but we need to investigate #69 before we cook 1.10.0 (to be done shortly)...
